{"errorMessage": "module 'os' has no attribute 'add_dll_directory'", "errorType": "AttributeError", "requestId": "", "stackTrace": ["  File \"/var/lang/lib/python3.11/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n", "  File \"<frozen importlib._bootstrap>\", line 1204, in _gcd_import\n", "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n", "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n", "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n", "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n", "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n", "  File \"/var/task/handler.py\", line 2, in <module>\n    import numpy as np\n", "  File \"/var/task/numpy/__init__.py\", line 98, in <module>\n    _delvewheel_patch_1_8_2()\n", "  File \"/var/task/numpy/__init__.py\", line 95, in _delvewheel_patch_1_8_2\n    os.add_dll_directory(libs_dir)\n"]}